<a href="https://colab.research.google.com/github/jenoshan/ML_in_python/blob/Lab_02/Lab_Session_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 01

## 1.1 Training a Decision Tree Classifer

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

fearures = iris.data
target = iris.target

In [ ]:
decisiontree = DecisionTreeClassifier(random_state=0)

In [ ]:
model = decisiontree.fit(fearures, target)

In [ ]:
observation = [[5,4,3,2]]

In [ ]:
model.predict(observation)

array([1])

In [ ]:
model.predict_proba(observation)

array([[0., 1., 0.]])

## 1.2 Controlling the tree size

In [ ]:
decisiontree = DecisionTreeClassifier(random_state = 0,
                                      max_depth = None,
                                      min_samples_split = 2,
                                      min_samples_leaf = 2,
                                      max_leaf_nodes = 3,
                                      min_impurity_decrease = 0)

In [ ]:
model = decisiontree.fit(fearures, target)

# Section 02

## 2.1 Creating a K-Nearest Neighbor Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [ ]:
standardizer = StandardScaler()

In [ ]:
x_std = standardizer.fit_transform(x)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1).fit(x_std, y)

In [ ]:
new_observations = [[0.75,0.75,0.75,0.75],
                    [1,1,1,1]]

In [ ]:
knn.predict(new_observations)

array([1, 2])

# Section 03

## 3.1 Training a Binary Classifier

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = datasets.load_iris()
features = iris.data[:100,:]
target = iris.target[:100]


In [ ]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [ ]:
logistic_regression = LogisticRegression(random_state=0)

In [ ]:
model = logistic_regression.fit(features_standardized, target)

In [ ]:
new_observations = [[0.5,0.5,0.5,0.5]]

In [ ]:
model.predict(new_observations)

array([1])

In [ ]:
model.predict_proba(new_observations)

array([[0.17738424, 0.82261576]])

## 3.2 Training a Multiclass Classifier 

In [ ]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [ ]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [ ]:
logistic_regression = LogisticRegression(random_state=0, multi_class="ovr")

In [ ]:
model = logistic_regression.fit(features_standardized, target)

## 3.3 Reducing Variance Through Regularization

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

In [ ]:
logistic_regression = LogisticRegressionCV(penalty='l2', Cs=10, random_state=0, n_jobs=-1)

In [ ]:
model = logistic_regression.fit(features_standardized, target)

## 3.4 Handling Imbalanced Classes

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [ ]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [ ]:
features = features[40:,:]
target = target[40:]

In [ ]:
target = np.where((target==0), 0, 1)

In [ ]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [ ]:
logistic_regression = LogisticRegression(random_state=0, class_weight="balanced")

In [ ]:
model = logistic_regression.fit(features_standardized, target)

# Section 04

## 4.1 Training a Linear Classifier

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
iris = datasets.load_iris()
features = iris.data[:100,:2]
target = iris.target[:100]

In [ ]:
features_standardized = scaler.fit_transform(features)

In [ ]:
svc = LinearSVC(C=1.0)

In [ ]:
model = svc.fit(features_standardized, target)

In [ ]:
new_observations = [[-2, 3]]

In [ ]:
svc.predict(new_observations)

array([0])

## 4.2 Creating Predicted Probabilites

In [ ]:
from sklearn.svm import SVC

In [ ]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [ ]:
features_standardized = scaler.fit_transform(features)

In [ ]:
svc = SVC(kernel="linear", probability=True, random_state=0)

In [ ]:
model = svc.fit(features_standardized, target)

In [ ]:
new_observations = [[.4,.4,.4,.4]]

In [ ]:
model.predict_proba(new_observations)

array([[0.00623541, 0.96973799, 0.0240266 ]])

## 4.3 Intentifying Support Vectors

In [ ]:
iris = datasets.load_iris()
features = iris.data[:100,:]
target = iris.target[:100]

In [ ]:
features_standardized = scaler.fit_transform(features)

In [ ]:
svc = SVC(kernel="linear", random_state=0)

In [ ]:
model = svc.fit(features_standardized, target)

In [ ]:
model.support_vectors_

array([[-0.5810659 ,  0.42196824, -0.80497402, -0.50860702],
       [-1.52079513, -1.67737625, -1.08231219, -0.86427627],
       [-0.89430898, -1.4674418 ,  0.30437864,  0.38056609],
       [-0.5810659 , -1.25750735,  0.09637501,  0.55840072]])

# Section 05

## 5.1 Training a Classifier for contious features

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [ ]:
classifier = GaussianNB()

In [ ]:
model = classifier.fit(features, target)

In [ ]:
new_observations = [[4,4,4,.4]]

In [ ]:
model.predict(new_observations)

array([1])

## 5.2 Training a classifier for discrete and count features

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
text_data = np.array(['I love Brazil. Brazil!',
                      'Brazil is best',
                      'Germany beats both'])

In [ ]:
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

In [ ]:
features = bag_of_words.toarray()

In [ ]:
features

array([[0, 0, 0, 2, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 0]])

In [ ]:
target = np.array([0,0,1])

In [ ]:
classifier = MultinomialNB(class_prior=[0.25, 0.5])

In [ ]:
model = classifier.fit(features, target)

In [ ]:
new_observations = [[0,0,0,1,0,1,0]]

In [ ]:
model.predict(new_observations)

array([0])

## 5.3 Training a Naive Bayes classifier for Binary Features

In [ ]:
from sklearn.naive_bayes import BernoulliNB

In [ ]:
features = np.random.randint(2, size=(100, 3))

In [ ]:
target = np.random.randint(2, size=(100,1)).ravel()

In [ ]:
classifier = BernoulliNB(class_prior=[0.25, 0.5])

In [ ]:
model = classifier.fit(features, target)